"""Type stubs for the compiled ``mnem._mnem`` extension (#29).

The public, agent-facing API is the ergonomic layer in ``mnem`` itself; this
stub covers the raw binding it is built on.
"""


__version__: str

def version() -> str: ...

class Store:
    @staticmethod
    def init(path: str) -> Store: ...
    @staticmethod
    def open(path: str) -> Store: ...
    def root(self) -> str: ...
    def format_version(self) -> int: ...
    def head(self) -> str: ...
    def add(
        self,
        id: str,
        content: str,
        *,
        content_kind: str = ...,
        agent_step: str | None = ...,
        observation: str | None = ...,
        tool_call: str | None = ...,
        source: str | None = ...,
        note: str | None = ...,
        event_time: int | None = ...,
    ) -> str: ...
    def staged(self) -> list[tuple[str, str]]: ...
    def unstage(self, node_id: str) -> bool: ...
    def commit(self, message: str, author: str, time_ms: int) -> str: ...
    def log(
        self, *, first_parent: bool = ..., limit: int | None = ...
    ) -> list[dict[str, object]]: ...

class MnemError(Exception): ...
class NotFoundError(MnemError): ...
class InvalidRefError(MnemError): ...
class ConflictError(MnemError): ...
class CorruptStoreError(MnemError): ...
class FormatVersionError(MnemError): ...
class StoreExistsError(MnemError): ...
class NoStoreError(MnemError): ...
class StoreIoError(MnemError): ...
